import { IAgenda } from "../models/agenda";

export const agenda: IAgenda[] = [
  {
    title: 'Registration',
    speakerName: '',
    speakerPosition: '',
    speakerImage: 'assets/images/agenda/registration.png',
    startTime: '8:00 AM',
    endTime: '9:00 AM',
    description: '',
  },
  {
    title: 'Session 1 - Angular 19 Features',
    speakerName: 'Yet to be decided',
    speakerPosition: '',
    speakerImage: 'assets/images/agenda/default.jpg',
    startTime: '9:00 AM',
    endTime: '9:30 AM',
    description: '',
  },
  {
    title: 'Session 2 - Angular 19 Features',
    speakerName: 'Yet to be decided',
    speakerPosition: '',
    speakerImage: 'assets/images/agenda/default.jpg',
    startTime: '9:30 AM',
    endTime: '10:00 AM',
    description: '',
  },
  {
    title: 'Speaker Felicitation',
    speakerName: '',
    speakerPosition: '',
    speakerImage: 'assets/images/agenda/award.png',
    startTime: '10:00 AM',
    endTime: '10:30 AM',
    description: '',
  },
  {
    title: 'Keynote',
    speakerName: 'Michael Hladky',
    speakerPosition: 'CEO @push-based.io',
    speakerImage: 'assets/images/speakers/michael-hladky.jpeg',
    startTime: '10:30 AM',
    endTime: '11:00 AM',
    description: '',
  },
  {
    title: 'Session 4',
    speakerName: 'Marko Stanimirović',
    speakerPosition: 'Principal Frontend Engineer',
    speakerImage: 'assets/images/speakers/marko-stanimirovic.jpg',
    startTime: '11:00 PM',
    endTime: '11:30 PM',
    description: '',
  },
  {
    title: 'Session 3',
    speakerName: 'Enea Jahollari',
    speakerPosition: 'GDE, Trainer, Senior Software Engineer',
    speakerImage: 'assets/images/speakers/enea-jahollari.webp',
    startTime: '11:30 AM',
    endTime: '12:00 PM',
    description: '',
  },
  {
    title: 'Micro Frontends: Necessity, Implementation, and Challenges',
    speakerName: 'Rainer Hahnekamp',
    speakerPosition: 'Trainer and Consultant @AngularArchitects.io',
    speakerImage: 'assets/images/speakers/rainer-hahnekamp.jpg',
    startTime: '12:00 AM',
    endTime: '12:30 PM',
    description:
      '<b>Micro Frontends</b> are a hot topic, promising an architecture where multiple teams can work independently on a single application, making their own technical choices while remaining isolated from each other. Sounds ideal, right? <br/> <br/> But it’s worth considering the trade-offs. While Micro Frontends offer unique benefits, they also introduce overhead and can come with unexpected challenges. <br/> <br/> In this talk, I’ll provide an <b>honest overview of the technical possibilities </b>, along with the pros and cons of each approach. You’ll learn about iFrame integration, Web Components, Native & Module Federation, and see these techniques in action. <br/> <br/> For some, Micro Frontends are a <b>no-go</b>; for others, they’re an option or <b>even an absolute necessity</b>. By the end of my talk, you should know which group you belong to.',
  },
  {
    title: 'Session 7',
    speakerName: 'Dhananjay Kumar',
    speakerPosition: 'Founder @NomadCoder| ng-India',
    speakerImage: 'assets/images/speakers/dhananjay-kumar.jpeg',
    startTime: '12:30 PM',
    endTime: '1:00 PM',
    description: '',
  },
  {
    title: 'Lunch Break',
    speakerName: '',
    speakerPosition: '',
    speakerImage: 'assets/images/agenda/lunch-break.png',
    startTime: '1:00 PM',
    endTime: '2:00 PM',
    description: '',
  },
  {
    title: 'Session 8',
    speakerName: 'Julian Jandl',
    speakerPosition: 'Lead Performance Engineer',
    speakerImage: 'assets/images/speakers/julian-jandl.webp',
    startTime: '2:00 PM',
    endTime: '2:30 PM',
    description: '',
  },
  {
    title: 'Session 9',
    speakerName: 'Christopher Holder',
    speakerPosition: 'Full Stack Engineer @ push-based.io',
    speakerImage: 'assets/images/speakers/chris-holder.png',
    startTime: '2:30 PM',
    endTime: '3:00 PM',
    description: '',
  },
  {
    title: 'Session 10',
    speakerName: 'Vojtech Mašek',
    speakerPosition: 'Head of Engineering @ flowup',
    speakerImage: 'assets/images/speakers/vojtech-masek.png',
    startTime: '3:00 PM',
    endTime: '3:30 PM',
    description: '',
  },
  {
    title: 'Session 11',
    speakerName: 'Tomas Trajan',
    speakerPosition: 'GDE | Founder of angularexperts.io',
    speakerImage: 'assets/images/speakers/tomas-trajan.jpeg',
    startTime: '3:30 PM',
    endTime: '4:00 PM',
    description: '',
  },
  {
    title: 'Tea Break',
    speakerName: '',
    speakerPosition: '',
    speakerImage: 'assets/images/agenda/tea-cup.png',
    startTime: '4:00 PM',
    endTime: '4:30 PM',
    description: '',
  },
  {
    title: 'Session 12',
    speakerName: 'Tomasz Ducin',
    speakerPosition: 'Consultant, Architect, Developer & Trainer',
    speakerImage: 'assets/images/speakers/tomasz-ducin.webp',
    startTime: '4:30 PM',
    endTime: '5:00 PM',
    description: '',
  },
  {
    title: 'Session 13',
    speakerName: 'Markus Ingvarsson',
    speakerPosition: 'Full-stack Developer @Consat Telematics',
    speakerImage: 'assets/images/speakers/markus-ingvarsson.jpeg',
    startTime: '5:00 PM',
    endTime: '5:30 PM',
    description: '',
  },
  {
    title: 'Session 14',
    speakerName: 'Pankaj Parkar',
    speakerPosition: 'Principal Application Developer @AON',
    speakerImage: 'assets/images/speakers/pankaj-parkar.jpeg',
    startTime: '5:30 PM',
    endTime: '6:00 PM',
    description: '',
  },
];