import { IAgenda } from "../models/agenda";

export const agenda: IAgenda[] = [
  {
    title: 'Registration',
    speakerName: '',
    speakerPosition: '',
    speakerImage: 'assets/images/agenda/registration.png',
    startTime: '8:00 AM',
    endTime: '9:00 AM',
    description: '',
  },
  {
    title: 'TBD',
    speakerName: 'Markus Ingvarsson',
    speakerPosition: 'Full-stack Developer @Consat Telematics',
    speakerImage: 'assets/images/speakers/markus-ingvarsson.jpeg',
    startTime: '9.00 AM',
    endTime: '9:30 AM',
    description: '',
  },
  // {
  //   title: 'TBD',
  //   speakerName: 'Kasia Biernat-Kluba',
  //   speakerPosition: 'Principal Software Engineer',
  //   speakerImage: 'assets/images/agenda/default.jpg',
  //   startTime: '9:30 AM',
  //   endTime: '9:45 AM',
  //   description: '',
  // },
  {
    title: 'TBD',
    speakerName: 'Kasia Biernat-Kluba',
    speakerPosition: 'Principal Software Engineer',
    speakerImage: 'assets/images/speakers/kasia.jpeg',
    startTime: '9:30 AM',
    endTime: '9:45 AM',
    description: '',
  },
  {
    title: 'Using Deferrable Views',
    speakerName: 'Shweta Mulik',
    speakerPosition: 'SDE-2 @AGCO',
    speakerImage: 'assets/images/speakers/shweta-mulik.jpeg',
    startTime: '9:45 AM',
    endTime: '10:00 AM',
    description: '',
  },
  {
    title: 'Speaker Felicitation',
    speakerName: '',
    speakerPosition: '',
    speakerImage: 'assets/images/agenda/award.png',
    startTime: '10:00 AM',
    endTime: '10:30 AM',
    description: '',
  },
  {
    title: 'Keynote',
    speakerName: 'Michael Hladky',
    speakerPosition: 'CEO @push-based.io',
    speakerImage: 'assets/images/speakers/michael-hladky.jpeg',
    startTime: '10:30 AM',
    endTime: '11:00 AM',
    description: '',
  },
  {
    title: 'Micro Frontends: Necessity, Implementation, and Challenges',
    speakerName: 'Rainer Hahnekamp',
    speakerPosition: 'Trainer and Consultant @AngularArchitects.io',
    speakerImage: 'assets/images/speakers/rainer-hahnekamp.jpg',
    startTime: '11:00 AM',
    endTime: '11:30 PM',
    description:
      '<b>Micro Frontends</b> are a hot topic, promising an architecture where multiple teams can work independently on a single application, making their own technical choices while remaining isolated from each other. Sounds ideal, right? <br/> <br/> But it’s worth considering the trade-offs. While Micro Frontends offer unique benefits, they also introduce overhead and can come with unexpected challenges. <br/> <br/> In this talk, I’ll provide an <b>honest overview of the technical possibilities </b>, along with the pros and cons of each approach. You’ll learn about iFrame integration, Web Components, Native & Module Federation, and see these techniques in action. <br/> <br/> For some, Micro Frontends are a <b>no-go</b>; for others, they’re an option or <b>even an absolute necessity</b>. By the end of my talk, you should know which group you belong to.',
  },
  {
    title: 'Getting Started With Signals',
    speakerName: 'Dhananjay Kumar',
    speakerPosition: 'Founder @NomadCoder| ng-India',
    speakerImage: 'assets/images/speakers/dj.jpeg',
    startTime: '11:30 PM',
    endTime: '12:00 PM',
    description: '',
  },
  {
    title: 'Build on top of Signals',
    speakerName: 'Enea Jahollari',
    speakerPosition: 'GDE, Trainer, Senior Software Engineer',
    speakerImage: 'assets/images/speakers/enea-jahollari.webp',
    startTime: '12:00 AM',
    endTime: '12:30 PM',
    description:
      'Angular <b> Signals </b> are a game-changer. But we can go even further.<br/><br/>This talk unveils how to build powerful utility functions, leveraging <b>inject </b> and <b>DestroyRef</b> to supercharge your Signals. Learn how to create reusable reactive patterns, simplify your code, and embrace a new <b> "synchronization" </b> mindset that optimizes performance. <br/><br/>Prepare to level up your Angular development with the building blocks of the future!',
  },
  {
    title: 'Event-Based State Management with NgRx SignalStore',
    speakerName: 'Marko Stanimirović',
    speakerPosition: 'Principal Frontend Engineer',
    speakerImage: 'assets/images/speakers/marko-stanimirovic.jpg',
    startTime: '12:30 PM',
    endTime: '1:00 PM',
    description:
      '<b>Event-driven architecture </b> adds a layer of indirection that enhances decoupling, improves data flow predictability, and supports the scaling of complex systems. <br/><br/> While SignalStore does not natively support an event-based model, its flexible and highly extensible design opens the door to integrating various functionalities and applying diverse state management patterns. <br/><br/> In this talk, we will explore how event-driven principles can be used with SignalStore to enhance and scale the <b>state management layer </b> in complex Angular applications.',
  },
  {
    title: 'Lunch Break',
    speakerName: '',
    speakerPosition: '',
    speakerImage: 'assets/images/agenda/lunch-break.png',
    startTime: '1:00 PM',
    endTime: '2:00 PM',
    description: '',
  },
  {
    title:
      'Long term success of your Angular projects with automated architecture validation',
    speakerName: 'Tomas Trajan',
    speakerPosition: 'Frontend Architect | Trainer @angularexperts.io',
    speakerImage: 'assets/images/speakers/tomas-trajan.jpeg',
    startTime: '2:00 PM',
    endTime: '2:30 PM',
    description:
      'Learn how to <b>architect</b> a brand new or improve an existing enterprise grade Angular application with a bulletproof <b>ESLINT</b> based automated architecture validation to guarantee that Your project stays maintainable, extendable and therefore allows you and your team to deliver consistently and with high velocity over the entire project lifetime!',
  },
  {
    title: 'TBD',
    speakerName: 'Vojtech Mašek',
    speakerPosition: 'Head of Engineering @ flowup',
    speakerImage: 'assets/images/speakers/vojtech-masek.png',
    startTime: '2:30 PM',
    endTime: '3:00 PM',
    description: '',
  },
  {
    title: 'Instant Navigation in Angular Applications',
    speakerName: 'Christopher Holder',
    speakerPosition: 'Full Stack Engineer @ push-based.io',
    speakerImage: 'assets/images/speakers/chris-holder.png',
    startTime: '3:00 PM',
    endTime: '3:30 PM',
    description:
      'Users spend 90% of their time interacting with applications after they load, but most developers just focus on speeding up the initial load. <br/> <br/> In this talk we will go beyond initial loading strategies, and make future navigation feel instant by predicting what users might click on next and loading those parts ahead of time. <br/><br/> We will use real applications to see how to implement speculative loading techniques and how you can measure the improvement with soft navigation  largest contentful paint (LCP). <br/><br/> Finally we will demonstrate how you can convert a 2 second navigation into less than 100 milliseconds using the Intersection Observer API, the Angular router and HTML link tags. <br/><br/> <b><u>Takeaways</u></b><br/><br/>Attendees will learn about the soft navigations and how that is about to change the way we measure performance on SPAs. Then they will learn an optimization framework to optimize their own applications using techniques inspired by the Speculative Rules API. They will see through an example that this can improve user experience and future navigations making them feel instant.',
  },
  {
    title: 'Sponsor Talk',
    speakerName: 'Sponsors',
    speakerPosition: 'Sponsors',
    speakerImage: 'assets/images/agenda/default.jpg',
    startTime: '3:30 PM',
    endTime: '4.00 PM',
    description: '',
  },
  {
    title: 'Tea Break',
    speakerName: '',
    speakerPosition: '',
    speakerImage: 'assets/images/agenda/tea-cup.png',
    startTime: '4:00 PM',
    endTime: '4:30 PM',
    description: '',
  },
  {
    title: 'TBD',
    speakerName: 'Tomasz Ducin',
    speakerPosition: 'Consultant, Architect, Developer & Trainer',
    speakerImage: 'assets/images/speakers/tomasz-ducin.webp',
    startTime: '4:30 PM',
    endTime: '5:00 PM',
    description: '',
  },
  {
    title: 'Virtual Views- Rendering What Matters, When It Matters',
    speakerName: 'Julian Jandl',
    speakerPosition: 'Lead Performance Engineer',
    speakerImage: 'assets/images/speakers/julian-jandl.webp',
    startTime: '5:00 PM',
    endTime: '5:30 PM',
    description:
      'A large number of DOM elements can significantly impact performance, leading to slow performing applications.Mobile users especially operate on limited hardware with smaller viewports. Most of the app contents are hidden below the fold. So why render them at all?<br/><br/> Virtual scrolling has long been a cornerstone of optimizing large lists and data-heavy applications, but it is not without its limitations. <br/></br/> This talk will introduce you to a more versatile solution for rendering only what matters, when it matters - RxAngulars Virtual View Directive. <br/><br/> <u><b>Takeaways</b></u> <br/><br/> <ul><li> *How and why large amounts of DOM negatively impact INP<li> <li>*The main principles of virtual scrolling</li><li>*The key differences between virtual scrolling and virtual views, and why this new approach is better suited for certain scenarios </li><li>*Practical tips for integrating virtual views into your projects, with real-world examples that demonstrate its versatility and performance benefits</li></ul>',
  },
  {
    title: 'Local and Zoneless Change Detection ',
    speakerName: 'Pankaj Parkar',
    speakerPosition: 'Principal Application Developer @AON',
    speakerImage: 'assets/images/speakers/pankaj-parkar.jpeg',
    startTime: '5:30 PM',
    endTime: '6:00 PM',
    description:
      'In modern web development, achieving efficient, scalable, and reactive applications is paramount. Traditional <b>change detection</b> strategies often rely on Angular <b>Zone.js </b>, while powerful, can introduce performance bottlenecks and complexity in large-scale applications. <br/><br/>This talk dives into the evolution of change detection, exploring how local and zoneless change detection strategies are transforming the way we synchronize state and update views.<br/> <br/> We will unravel the mechanics behind these approaches, demonstrate their impact on performance optimization, and showcase practical use cases.<br/><br/> Join us to discover the concept of synchronization and how you can architect applications to thrive in the new angular era',
  },
];